name: Build and test

on:
  push:
    branches: [ "**", "!main", "!production" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew -Pversion=${{ github.sha }} build

      - name: Test
        run: ./gradlew -Pversion=${{ github.sha }} test
