name: Update CHANGELOG.md and create git tag

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.15.0
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
        with:
          tag_name: ${{ steps.changelog.outpus.tag }}
          release_name: ${{ steps.changelog.outpus.tag }}
          body: ${{ steps.changelog.outpus.clean_changelog }}
