name: Create GitHub Release

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.14
