name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.15.0
      - name: Print tag name
        run: echo ${{ steps.changelog.outputs.tag }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
